package com.fortinet.fmg.ws.r200806;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-12-30T19:06:46.292+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://r200806.ws.fmg.fortinet.com/", name = "FortiManagerWSPortType")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
public interface FortiManagerWSPortType {

    @RequestWrapper(localName = "installConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.InstallConfig")
    @WebMethod
    @ResponseWrapper(localName = "installConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.InstallConfigResponse")
    public void installConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "from", targetNamespace = "")
        java.lang.String from,
        @WebParam(name = "to", targetNamespace = "")
        java.lang.String to,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "pkgoid", targetNamespace = "")
        java.math.BigInteger pkgoid,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "newRevName", targetNamespace = "")
        java.lang.String newRevName,
        @WebParam(name = "instValidate", targetNamespace = "")
        java.lang.Boolean instValidate,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> taskId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importPolicy", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ImportPolicy")
    @WebMethod
    @ResponseWrapper(localName = "importPolicyResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ImportPolicyResponse")
    public com.fortinet.fmg.ws.r200806.ImportPolicy importPolicy(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(mode = WebParam.Mode.INOUT, name = "adomName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> adomName,
        @WebParam(mode = WebParam.Mode.INOUT, name = "adomOid", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> adomOid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "devName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> devName,
        @WebParam(mode = WebParam.Mode.INOUT, name = "devId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> devId,
        @WebParam(name = "vdomName", targetNamespace = "")
        java.lang.String vdomName,
        @WebParam(name = "vdomId", targetNamespace = "")
        java.lang.Integer vdomId,
        @WebParam(name = "policyPackageName", targetNamespace = "")
        java.lang.String policyPackageName,
        @WebParam(mode = WebParam.Mode.OUT, name = "vdoms", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.VdomInfo>> vdoms,
        @WebParam(mode = WebParam.Mode.OUT, name = "report", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> report,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg
    ) throws InvalidServicePassException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getTCLRootFileResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", partName = "parameters")
    @WebMethod
    public GetTCLRootFileResponse getTCLRootFile(
        @WebParam(partName = "parameters", name = "getTCLRootFile", targetNamespace = "http://r200806.ws.fmg.fortinet.com/")
        GetTCLRootFile parameters
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getScriptLogSummary", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScriptLogSummary")
    @WebMethod
    @ResponseWrapper(localName = "getScriptLogSummaryResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScriptLogSummaryResponse")
    public java.util.List<com.fortinet.fmg.ws.r200806.ScriptLogSummary> getScriptLogSummary(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "maxLogs", targetNamespace = "")
        java.lang.Integer maxLogs,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getScript", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScript")
    @WebMethod
    @ResponseWrapper(localName = "getScriptResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScriptResponse")
    public com.fortinet.fmg.ws.r200806.ScriptInfo getScript(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "setFazConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.SetFazConfig")
    @WebMethod
    @ResponseWrapper(localName = "setFazConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.SetFazConfigResponse")
    public void setFazConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "config", targetNamespace = "")
        java.lang.String config,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "cliError", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> cliError,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorLineNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> errorLineNumber
    ) throws InvalidServicePassException, TooManyEntriesException;

    @WebResult(name = "instLog", targetNamespace = "")
    @RequestWrapper(localName = "getInstlog", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetInstlog")
    @WebMethod
    @ResponseWrapper(localName = "getInstlogResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetInstlogResponse")
    public com.fortinet.fmg.ws.r200806.InstLog getInstlog(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "taskId", targetNamespace = "")
        java.math.BigInteger taskId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeviceVdomList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceVdomList")
    @WebMethod
    @ResponseWrapper(localName = "getDeviceVdomListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceVdomListResponse")
    public java.util.List<com.fortinet.fmg.ws.r200806.VdomInfo> getDeviceVdomList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devName", targetNamespace = "")
        java.lang.String devName,
        @WebParam(name = "devID", targetNamespace = "")
        java.math.BigInteger devID,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(mode = WebParam.Mode.OUT, name = "oid", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> oid
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "addWTP", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddWTP")
    @WebMethod
    @ResponseWrapper(localName = "addWTPResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddWTPResponse")
    public void addWTP(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "deviceName", targetNamespace = "")
        java.lang.String deviceName,
        @WebParam(name = "vdomName", targetNamespace = "")
        java.lang.String vdomName,
        @WebParam(name = "comment", targetNamespace = "")
        java.lang.String comment,
        @WebParam(name = "powerLevel", targetNamespace = "")
        java.lang.Integer powerLevel,
        @WebParam(name = "vaps", targetNamespace = "")
        java.util.List<java.lang.String> vaps,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> taskId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "getGroupList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetGroupList")
    @WebMethod
    @ResponseWrapper(localName = "getGroupListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetGroupListResponse")
    public void getGroupList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "detail", targetNamespace = "")
        java.lang.Boolean detail,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.GroupInfo>> groupInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.GroupDetail>> groupDetail
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "listFazGeneratedReports", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ListFazGeneratedReports")
    @WebMethod
    @ResponseWrapper(localName = "listFazGeneratedReportsResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ListFazGeneratedReportsResponse")
    public void listFazGeneratedReports(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "totalNumberExists", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> totalNumberExists,
        @WebParam(mode = WebParam.Mode.OUT, name = "reportList", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.ListFazGeneratedReportsResponse.ReportList>> reportList
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "addGroup", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddGroup")
    @WebMethod
    @ResponseWrapper(localName = "addGroupResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddGroupResponse")
    public void addGroup(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "deviceSN", targetNamespace = "")
        java.util.List<java.lang.String> deviceSN,
        @WebParam(name = "deviceID", targetNamespace = "")
        java.util.List<java.math.BigInteger> deviceID,
        @WebParam(name = "groupName", targetNamespace = "")
        java.util.List<java.lang.String> groupName,
        @WebParam(name = "groupID", targetNamespace = "")
        java.util.List<java.math.BigInteger> groupID,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "grpId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> grpId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPackageList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetPackageList")
    @WebMethod
    @ResponseWrapper(localName = "getPackageListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetPackageListResponse")
    public java.util.List<com.fortinet.fmg.ws.r200806.PackageInfo> getPackageList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "isGlobal", targetNamespace = "")
        java.lang.Boolean isGlobal
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getFazArchive", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazArchive")
    @WebMethod
    @ResponseWrapper(localName = "getFazArchiveResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazArchiveResponse")
    public void getFazArchive(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "devId", targetNamespace = "")
        java.lang.String devId,
        @WebParam(name = "type", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ArchiveTypes type,
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "checksum", targetNamespace = "")
        java.lang.String checksum,
        @WebParam(name = "zipPassword", targetNamespace = "")
        java.lang.String zipPassword,
        @WebParam(name = "compression", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.CompressionType compression,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "fileList", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.GetFazArchiveResponse.FileList>> fileList,
        @WebParam(mode = WebParam.Mode.OUT, name = "archiveFile", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> archiveFile
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "listRevisionId", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ListRevisionId")
    @WebMethod
    @ResponseWrapper(localName = "listRevisionIdResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.ListRevisionIdResponse")
    public void listRevisionId(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "revName", targetNamespace = "")
        java.lang.String revName,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "revId", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<java.lang.Integer>> revId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "getAdomList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetAdomList")
    @WebMethod
    @ResponseWrapper(localName = "getAdomListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetAdomListResponse")
    public void getAdomList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "detail", targetNamespace = "")
        java.lang.Boolean detail,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "adomInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.AdomInfo>> adomInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "adomDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.AdomDetail>> adomDetail
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getGroups", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetGroups")
    @WebMethod
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetGroupsResponse")
    public void getGroups(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "names", targetNamespace = "")
        java.util.List<java.lang.String> names,
        @WebParam(name = "grpIds", targetNamespace = "")
        java.util.List<java.math.BigInteger> grpIds,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.GroupDetail>> groupDetail
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "retrieveConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RetrieveConfig")
    @WebMethod
    @ResponseWrapper(localName = "retrieveConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RetrieveConfigResponse")
    public void retrieveConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.lang.String devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "newRevName", targetNamespace = "")
        java.lang.String newRevName,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> taskId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeviceLicenseList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceLicenseList")
    @WebMethod
    @ResponseWrapper(localName = "getDeviceLicenseListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceLicenseListResponse")
    public com.fortinet.fmg.ws.r200806.DeviceLicenseList getDeviceLicenseList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "addAdom", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddAdom")
    @WebMethod
    @ResponseWrapper(localName = "addAdomResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddAdomResponse")
    public void addAdom(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "version", targetNamespace = "")
        int version,
        @WebParam(name = "mr", targetNamespace = "")
        int mr,
        @WebParam(name = "isBackupMode", targetNamespace = "")
        java.lang.Boolean isBackupMode,
        @WebParam(name = "VPNManagement", targetNamespace = "")
        java.lang.Boolean vpnManagement,
        @WebParam(name = "deviceSNVdom", targetNamespace = "")
        java.util.List<com.fortinet.fmg.ws.r200806.DevSNVdom> deviceSNVdom,
        @WebParam(name = "deviceIDVdom", targetNamespace = "")
        java.util.List<com.fortinet.fmg.ws.r200806.DevIDVdom> deviceIDVdom,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "adomOid", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> adomOid
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "assignGlobalPolicy", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AssignGlobalPolicy")
    @WebMethod
    @ResponseWrapper(localName = "assignGlobalPolicyResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AssignGlobalPolicyResponse")
    public void assignGlobalPolicy(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "policyPackageName", targetNamespace = "")
        java.lang.String policyPackageName,
        @WebParam(name = "policyPackageOid", targetNamespace = "")
        java.math.BigInteger policyPackageOid,
        @WebParam(name = "adomList", targetNamespace = "")
        java.util.List<com.fortinet.fmg.ws.r200806.AdomTarget> adomList,
        @WebParam(name = "allObjects", targetNamespace = "")
        java.lang.Boolean allObjects,
        @WebParam(name = "installToDevice", targetNamespace = "")
        java.lang.Boolean installToDevice,
        @WebParam(name = "checkAssigndDup", targetNamespace = "")
        java.lang.Boolean checkAssigndDup,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> taskId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "runScript", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RunScript")
    @WebMethod
    @ResponseWrapper(localName = "runScriptResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RunScriptResponse")
    public void runScript(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "isGlobal", targetNamespace = "")
        java.lang.Boolean isGlobal,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "devId", targetNamespace = "")
        java.lang.String devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "runOnDB", targetNamespace = "")
        java.lang.Boolean runOnDB,
        @WebParam(name = "pkgoid", targetNamespace = "")
        java.math.BigInteger pkgoid,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> taskId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetConfig")
    @WebMethod
    @ResponseWrapper(localName = "getConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetConfigResponse")
    public com.fortinet.fmg.ws.r200806.ConfigRevisionInfo getConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "revisionNumber", targetNamespace = "")
        java.lang.Integer revisionNumber
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "deleteConfigRev", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteConfigRev")
    @WebMethod
    @ResponseWrapper(localName = "deleteConfigRevResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteConfigRevResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg deleteConfigRev(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "revName", targetNamespace = "")
        java.lang.String revName,
        @WebParam(name = "revId", targetNamespace = "")
        java.lang.Integer revId
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "deleteAdom", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteAdom")
    @WebMethod
    @ResponseWrapper(localName = "deleteAdomResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteAdomResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg deleteAdom(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adomName", targetNamespace = "")
        java.lang.String adomName,
        @WebParam(name = "adomOid", targetNamespace = "")
        java.math.BigInteger adomOid
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "deleteDevice", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteDevice")
    @WebMethod
    @ResponseWrapper(localName = "deleteDeviceResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteDeviceResponse")
    public void deleteDevice(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> taskId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "addDevice", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddDevice")
    @WebMethod
    @ResponseWrapper(localName = "addDeviceResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddDeviceResponse")
    public void addDevice(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "ip", targetNamespace = "")
        java.lang.String ip,
        @WebParam(name = "autod", targetNamespace = "")
        java.lang.String autod,
        @WebParam(name = "deviceType", targetNamespace = "")
        java.lang.String deviceType,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "adminUser", targetNamespace = "")
        java.lang.String adminUser,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "version", targetNamespace = "")
        java.lang.Integer version,
        @WebParam(name = "mr", targetNamespace = "")
        java.lang.Integer mr,
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "flags", targetNamespace = "")
        java.lang.String flags,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "devId", targetNamespace = "")
        java.lang.String devId,
        @WebParam(name = "SN", targetNamespace = "")
        java.lang.String sn,
        @WebParam(name = "SNprefix", targetNamespace = "")
        java.lang.String sNprefix,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> taskId
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getConfigRevisionHistory", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetConfigRevisionHistory")
    @WebMethod
    @ResponseWrapper(localName = "getConfigRevisionHistoryResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetConfigRevisionHistoryResponse")
    public java.util.List<com.fortinet.fmg.ws.r200806.ConfigRevisionInfo> getConfigRevisionHistory(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "checkinUser", targetNamespace = "")
        java.lang.String checkinUser,
        @WebParam(name = "minCheckinDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar minCheckinDate,
        @WebParam(name = "maxCheckinDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar maxCheckinDate,
        @WebParam(name = "minRevisionNumber", targetNamespace = "")
        java.lang.Integer minRevisionNumber,
        @WebParam(name = "maxRevisionNumber", targetNamespace = "")
        java.lang.Integer maxRevisionNumber
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getTaskList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetTaskList")
    @WebMethod
    @ResponseWrapper(localName = "getTaskListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetTaskListResponse")
    public void getTaskList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskList", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.TaskListInfo>> taskList
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "removeFazArchive", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RemoveFazArchive")
    @WebMethod
    @ResponseWrapper(localName = "removeFazArchiveResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RemoveFazArchiveResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg removeFazArchive(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "devId", targetNamespace = "")
        java.lang.String devId,
        @WebParam(name = "type", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ArchiveTypes type,
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "checksum", targetNamespace = "")
        java.lang.String checksum
    ) throws InvalidServicePassException, TooManyEntriesException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createScript", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.CreateScript")
    @WebMethod
    @ResponseWrapper(localName = "createScriptResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.CreateScriptResponse")
    public java.lang.Long createScript(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "isGlobal", targetNamespace = "")
        java.lang.Boolean isGlobal,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content,
        @WebParam(name = "overwrite", targetNamespace = "")
        java.lang.Boolean overwrite
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "getDeviceList", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceList")
    @WebMethod
    @ResponseWrapper(localName = "getDeviceListResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDeviceListResponse")
    public void getDeviceList(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "detail", targetNamespace = "")
        java.lang.Boolean detail,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "deviceInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.DeviceInfo>> deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "deviceDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.DeviceDetail>> deviceDetail
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getSystemStatus", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetSystemStatus")
    @WebMethod
    @ResponseWrapper(localName = "getSystemStatusResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetSystemStatusResponse")
    public void getSystemStatus(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "platformType", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> platformType,
        @WebParam(mode = WebParam.Mode.OUT, name = "version", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> version,
        @WebParam(mode = WebParam.Mode.OUT, name = "serialNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> serialNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "biosVersion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> biosVersion,
        @WebParam(mode = WebParam.Mode.OUT, name = "hostName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hostName,
        @WebParam(mode = WebParam.Mode.OUT, name = "maxNumAdminDomains", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> maxNumAdminDomains,
        @WebParam(mode = WebParam.Mode.OUT, name = "maxNumDeviceGroup", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> maxNumDeviceGroup,
        @WebParam(mode = WebParam.Mode.OUT, name = "adminDomainConf", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> adminDomainConf,
        @WebParam(mode = WebParam.Mode.OUT, name = "fipsMode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> fipsMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "diskSpaceFreeMB", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> diskSpaceFreeMB,
        @WebParam(mode = WebParam.Mode.OUT, name = "diskSpaceUsedMB", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> diskSpaceUsedMB
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "searchFazLog", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.SearchFazLog")
    @WebMethod
    @ResponseWrapper(localName = "searchFazLogResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.SearchFazLogResponse")
    public void searchFazLog(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "content", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.SearchContent content,
        @WebParam(name = "format", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.LogFormats format,
        @WebParam(name = "deviceName", targetNamespace = "")
        java.lang.String deviceName,
        @WebParam(name = "logType", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.LogTypes logType,
        @WebParam(name = "searchCriteria", targetNamespace = "")
        java.lang.String searchCriteria,
        @WebParam(name = "maxNumMatches", targetNamespace = "")
        int maxNumMatches,
        @WebParam(mode = WebParam.Mode.INOUT, name = "startIndex", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> startIndex,
        @WebParam(name = "checkArchive", targetNamespace = "")
        int checkArchive,
        @WebParam(name = "DLPArchiveType", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ArchiveTypes dlpArchiveType,
        @WebParam(name = "compression", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.CompressionType compression,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "totalResultsFound", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> totalResultsFound,
        @WebParam(mode = WebParam.Mode.OUT, name = "matchesReturned", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> matchesReturned,
        @WebParam(mode = WebParam.Mode.OUT, name = "logs", targetNamespace = "")
        javax.xml.ws.Holder<com.fortinet.fmg.ws.r200806.SearchFazLogResponse.Logs> logs
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getFazConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazConfig")
    @WebMethod
    @ResponseWrapper(localName = "getFazConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazConfigResponse")
    public void getFazConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "config", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> config
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "getAdoms", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetAdoms")
    @WebMethod
    @ResponseWrapper(localName = "getAdomsResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetAdomsResponse")
    public void getAdoms(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "names", targetNamespace = "")
        java.util.List<java.lang.String> names,
        @WebParam(name = "adomIds", targetNamespace = "")
        java.util.List<java.math.BigInteger> adomIds,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "adomDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.AdomDetail>> adomDetail
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "getDevices", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDevices")
    @WebMethod
    @ResponseWrapper(localName = "getDevicesResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetDevicesResponse")
    public void getDevices(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "serialNumbers", targetNamespace = "")
        java.util.List<java.lang.String> serialNumbers,
        @WebParam(name = "devIds", targetNamespace = "")
        java.util.List<java.math.BigInteger> devIds,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "deviceDetail", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.fortinet.fmg.ws.r200806.DeviceDetail>> deviceDetail
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "revertConfig", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RevertConfig")
    @WebMethod
    @ResponseWrapper(localName = "revertConfigResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RevertConfigResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg revertConfig(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "revId", targetNamespace = "")
        int revId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "runFazReport", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RunFazReport")
    @WebMethod
    @ResponseWrapper(localName = "runFazReportResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.RunFazReportResponse")
    public void runFazReport(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(mode = WebParam.Mode.INOUT, name = "reportTemplate", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> reportTemplate,
        @WebParam(name = "filter", targetNamespace = "")
        java.util.List<java.lang.String> filter,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "addPolicyPackage", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddPolicyPackage")
    @WebMethod
    @ResponseWrapper(localName = "addPolicyPackageResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.AddPolicyPackageResponse")
    public void addPolicyPackage(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "isGlobal", targetNamespace = "")
        java.lang.Boolean isGlobal,
        @WebParam(name = "policyPackageName", targetNamespace = "")
        java.lang.String policyPackageName,
        @WebParam(name = "cloneFrom", targetNamespace = "")
        java.lang.String cloneFrom,
        @WebParam(name = "rename", targetNamespace = "")
        java.lang.String rename,
        @WebParam(name = "packageInstallTarget", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.PackageInstallTarget packageInstallTarget,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "policyPackageOid", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> policyPackageOid,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskId", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> taskId
    ) throws InvalidServicePassException;

    @RequestWrapper(localName = "getFazGeneratedReport", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazGeneratedReport")
    @WebMethod
    @ResponseWrapper(localName = "getFazGeneratedReportResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetFazGeneratedReportResponse")
    public void getFazGeneratedReport(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "reportDate", targetNamespace = "")
        java.lang.String reportDate,
        @WebParam(mode = WebParam.Mode.INOUT, name = "reportName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> reportName,
        @WebParam(name = "compression", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.CompressionType compression,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "size", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> size,
        @WebParam(mode = WebParam.Mode.OUT, name = "fazReportData", targetNamespace = "")
        javax.xml.ws.Holder<FazReportData> fazReportData
    ) throws InvalidServicePassException, TooManyEntriesException;

    @RequestWrapper(localName = "deleteScript", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteScript")
    @WebMethod
    @ResponseWrapper(localName = "deleteScriptResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteScriptResponse")
    public void deleteScript(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    ) throws InvalidServicePassException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getScriptLog", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScriptLog")
    @WebMethod
    @ResponseWrapper(localName = "getScriptLogResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.GetScriptLogResponse")
    public com.fortinet.fmg.ws.r200806.ScriptLog getScriptLog(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "devId", targetNamespace = "")
        java.math.BigInteger devId,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "logId", targetNamespace = "")
        java.lang.Integer logId,
        @WebParam(name = "scriptName", targetNamespace = "")
        java.lang.String scriptName,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorMsg", targetNamespace = "")
        javax.xml.ws.Holder<ErrorMsg> errorMsg
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteGroup")
    @WebMethod
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.DeleteGroupResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg deleteGroup(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "grpId", targetNamespace = "")
        java.math.BigInteger grpId
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "editAdom", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.EditAdom")
    @WebMethod
    @ResponseWrapper(localName = "editAdomResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.EditAdomResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg editAdom(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "version", targetNamespace = "")
        java.lang.Integer version,
        @WebParam(name = "mr", targetNamespace = "")
        java.lang.Integer mr,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.Boolean state,
        @WebParam(name = "isBackupMode", targetNamespace = "")
        java.lang.Boolean isBackupMode,
        @WebParam(name = "VPNManagement", targetNamespace = "")
        java.lang.Boolean vpnManagement,
        @WebParam(name = "metafields", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.Metafields metafields,
        @WebParam(name = "addDeviceSNVdom", targetNamespace = "")
        java.util.List<com.fortinet.fmg.ws.r200806.DevSNVdom> addDeviceSNVdom,
        @WebParam(name = "addDeviceIDVdom", targetNamespace = "")
        java.util.List<com.fortinet.fmg.ws.r200806.DevIDVdom> addDeviceIDVdom
    ) throws InvalidServicePassException;

    @WebResult(name = "errorMsg", targetNamespace = "")
    @RequestWrapper(localName = "editGroupMembership", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.EditGroupMembership")
    @WebMethod
    @ResponseWrapper(localName = "editGroupMembershipResponse", targetNamespace = "http://r200806.ws.fmg.fortinet.com/", className = "com.fortinet.fmg.ws.r200806.EditGroupMembershipResponse")
    public com.fortinet.fmg.ws.r200806.ErrorMsg editGroupMembership(
        @WebParam(name = "servicePass", targetNamespace = "")
        com.fortinet.fmg.ws.r200806.ServicePass servicePass,
        @WebParam(name = "adom", targetNamespace = "")
        java.lang.String adom,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "grpId", targetNamespace = "")
        java.math.BigInteger grpId,
        @WebParam(name = "addDeviceSNList", targetNamespace = "")
        java.util.List<java.lang.String> addDeviceSNList,
        @WebParam(name = "addDeviceIDList", targetNamespace = "")
        java.util.List<java.math.BigInteger> addDeviceIDList,
        @WebParam(name = "delDeviceSNList", targetNamespace = "")
        java.util.List<java.lang.String> delDeviceSNList,
        @WebParam(name = "delDeviceIDList", targetNamespace = "")
        java.util.List<java.math.BigInteger> delDeviceIDList,
        @WebParam(name = "addGroupNameList", targetNamespace = "")
        java.util.List<java.lang.String> addGroupNameList,
        @WebParam(name = "addGroupIDList", targetNamespace = "")
        java.util.List<java.math.BigInteger> addGroupIDList,
        @WebParam(name = "delGroupNameList", targetNamespace = "")
        java.util.List<java.lang.String> delGroupNameList,
        @WebParam(name = "delGroupIDList", targetNamespace = "")
        java.util.List<java.math.BigInteger> delGroupIDList
    ) throws InvalidServicePassException;
}
