
package com.fortinet.fmg.ws.r200806;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-12-30T19:06:46.227+08:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "InvalidServicePassFault", targetNamespace = "http://r200806.ws.fmg.fortinet.com/")
public class InvalidServicePassException extends Exception {
    
    private com.fortinet.fmg.ws.r200806.InvalidServicePassFault invalidServicePassFault;

    public InvalidServicePassException() {
        super();
    }
    
    public InvalidServicePassException(String message) {
        super(message);
    }
    
    public InvalidServicePassException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidServicePassException(String message, com.fortinet.fmg.ws.r200806.InvalidServicePassFault invalidServicePassFault) {
        super(message);
        this.invalidServicePassFault = invalidServicePassFault;
    }

    public InvalidServicePassException(String message, com.fortinet.fmg.ws.r200806.InvalidServicePassFault invalidServicePassFault, Throwable cause) {
        super(message, cause);
        this.invalidServicePassFault = invalidServicePassFault;
    }

    public com.fortinet.fmg.ws.r200806.InvalidServicePassFault getFaultInfo() {
        return this.invalidServicePassFault;
    }
}
