
package com.fortinet.fmg.ws.r200806;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-12-30T19:06:46.277+08:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "TooManyEntriesFault", targetNamespace = "http://r200806.ws.fmg.fortinet.com/")
public class TooManyEntriesException extends Exception {
    
    private com.fortinet.fmg.ws.r200806.TooManyEntriesFault tooManyEntriesFault;

    public TooManyEntriesException() {
        super();
    }
    
    public TooManyEntriesException(String message) {
        super(message);
    }
    
    public TooManyEntriesException(String message, Throwable cause) {
        super(message, cause);
    }

    public TooManyEntriesException(String message, com.fortinet.fmg.ws.r200806.TooManyEntriesFault tooManyEntriesFault) {
        super(message);
        this.tooManyEntriesFault = tooManyEntriesFault;
    }

    public TooManyEntriesException(String message, com.fortinet.fmg.ws.r200806.TooManyEntriesFault tooManyEntriesFault, Throwable cause) {
        super(message, cause);
        this.tooManyEntriesFault = tooManyEntriesFault;
    }

    public com.fortinet.fmg.ws.r200806.TooManyEntriesFault getFaultInfo() {
        return this.tooManyEntriesFault;
    }
}
