package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigFirewallAddressHistory generated by hbm2java
 */
@Entity
@Table(name = "config_firewall_address_history", schema = "public")
public class ConfigFirewallAddressHistory extends BasicEntity {

	private ConfigFirewallAddress configFirewallAddress;
	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 所属Subnet
	 */
	private Integer subnet;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigFirewallAddressHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public ConfigFirewallAddress getConfigFirewallAddress() {
		return configFirewallAddress;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "subnet")
	public Integer getSubnet() {
		return subnet;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setConfigFirewallAddress(ConfigFirewallAddress configFirewallAddress) {
		this.configFirewallAddress = configFirewallAddress;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setSubnet(Integer subnet) {
		this.subnet = subnet;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
