package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigFirewallAddress generated by hbm2java
 */
@Entity
@Table(name = "config_firewall_address", schema = "public")
public class ConfigFirewallAddress extends BasicEntity {

	private Set<ConfigFirewallAddressHistory> configFirewallAddressHistories = new HashSet<ConfigFirewallAddressHistory>(
			0);

	/**
	 * 所属FirewallService
	 */
	private Integer firewallService;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 所属Subnet
	 */
	private Integer subnet;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigFirewallAddress() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configFirewallAddress")
	public Set<ConfigFirewallAddressHistory> getConfigFirewallAddressHistories() {
		return configFirewallAddressHistories;
	}

	@Column(name = "firewall_service")
	public Integer getFirewallService() {
		return firewallService;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "subnet")
	public Integer getSubnet() {
		return subnet;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setConfigFirewallAddressHistories(Set<ConfigFirewallAddressHistory> configFirewallAddressHistories) {
		this.configFirewallAddressHistories = configFirewallAddressHistories;
	}

	public void setFirewallService(Integer firewallService) {
		this.firewallService = firewallService;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setSubnet(Integer subnet) {
		this.subnet = subnet;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
