package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigRouterStatic generated by hbm2java
 */
@Entity
@Table(name = "config_router_static", schema = "public")
public class ConfigRouterStatic extends BasicEntity {

	private Set<ConfigRouterStaticHistory> configRouterStaticHistories = new HashSet<ConfigRouterStaticHistory>(0);

	/**
	 * 所属FirewallService
	 */
	private Integer firewallService;

	/**
	 * 所属ISP
	 */
	private Integer isp;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 防火墙路由ID,唯一递增
	 */
	private Integer routerId;

	/**
	 * 网段
	 */
	private String segment;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigRouterStatic() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configRouterStatic")
	public Set<ConfigRouterStaticHistory> getConfigRouterStaticHistories() {
		return configRouterStaticHistories;
	}

	@Column(name = "firewall_service")
	public Integer getFirewallService() {
		return firewallService;
	}

	@Column(name = "isp")
	public Integer getIsp() {
		return isp;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "router_id")
	public Integer getRouterId() {
		return routerId;
	}

	@Column(name = "segment", length = 100)
	public String getSegment() {
		return segment;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setConfigRouterStaticHistories(Set<ConfigRouterStaticHistory> configRouterStaticHistories) {
		this.configRouterStaticHistories = configRouterStaticHistories;
	}

	public void setFirewallService(Integer firewallService) {
		this.firewallService = firewallService;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setRouterId(Integer routerId) {
		this.routerId = routerId;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}
}
