package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigFirewallPolicy generated by hbm2java
 */
@Entity
@Table(name = "config_firewall_policy", schema = "public")
public class ConfigFirewallPolicy extends BasicEntity {

	private Set<ConfigFirewallPolicyHistory> configFirewallPolicies = new HashSet<ConfigFirewallPolicyHistory>(0);

	/**
	 * 目标地址
	 */
	private String dstaddr;

	/**
	 * 目标接口
	 */
	private String dstintf;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 策略类型:Internet or Subnet
	 */
	private Integer policyType;

	/**
	 * 源地址
	 */
	private String srcaddr;

	/**
	 * 源接口
	 */
	private String srcintf;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigFirewallPolicy() {
	}

 
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configFirewallPolicy")
	public Set<ConfigFirewallPolicyHistory> getConfigFirewallPolicies() {
		return configFirewallPolicies;
	}

	@Column(name = "dstaddr", length = 100)
	public String getDstaddr() {
		return dstaddr;
	}

	@Column(name = "dstintf", length = 100)
	public String getDstintf() {
		return dstintf;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "policy_type")
	public Integer getPolicyType() {
		return policyType;
	}

	@Column(name = "srcaddr", length = 100)
	public String getSrcaddr() {
		return srcaddr;
	}

	@Column(name = "srcintf", length = 100)
	public String getSrcintf() {
		return srcintf;
	}

	 
	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}


	public void setConfigFirewallPolicies(Set<ConfigFirewallPolicyHistory> configFirewallPolicies) {
		this.configFirewallPolicies = configFirewallPolicies;
	}


	public void setDstaddr(String dstaddr) {
		this.dstaddr = dstaddr;
	}

	public void setDstintf(String dstintf) {
		this.dstintf = dstintf;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setPolicyType(Integer policyType) {
		this.policyType = policyType;
	}

	public void setSrcaddr(String srcaddr) {
		this.srcaddr = srcaddr;
	}

	public void setSrcintf(String srcintf) {
		this.srcintf = srcintf;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
