package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigSystemInterface generated by hbm2java
 */
@Entity
@Table(name = "config_system_interface", schema = "public")
public class ConfigSystemInterface extends BasicEntity {

	private Set<ConfigSystemInterfaceHistory> configSystemInterfaceHistories = new HashSet<ConfigSystemInterfaceHistory>(
			0);

	/**
	 * 所属FirewallService
	 */
	private Integer firewallService;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * PortId
	 * 
	 * 接口名的组成格式为 "port"+"id" ,其中id 为 1-10 中一个.
	 */
	private Integer portId;

	/**
	 * 所属Subnet
	 */
	private Integer subnet;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigSystemInterface() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configSystemInterface")
	public Set<ConfigSystemInterfaceHistory> getConfigSystemInterfaceHistories() {
		return configSystemInterfaceHistories;
	}

	@Column(name = "firewall_service")
	public Integer getFirewallService() {
		return firewallService;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "port_id")
	public Integer getPortId() {
		return portId;
	}

	@Column(name = "subnet")
	public Integer getSubnet() {
		return subnet;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setConfigSystemInterfaceHistories(Set<ConfigSystemInterfaceHistory> configSystemInterfaceHistories) {
		this.configSystemInterfaceHistories = configSystemInterfaceHistories;
	}

	public void setFirewallService(Integer firewallService) {
		this.firewallService = firewallService;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setPortId(Integer portId) {
		this.portId = portId;
	}

	public void setSubnet(Integer subnet) {
		this.subnet = subnet;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
