package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigFirewallAddressHistory generated by hbm2java
 */
@Entity
@Table(name = "config_firewall_service_category_history", schema = "public")
public class ConfigFirewallServiceCategoryHistory extends BasicEntity {

	/**
	 * 行为 allow & deny
	 */
	private String action;

	/**
	 * IP地址, 下行时为源,上行时为目标
	 */
	private String address;

	private ConfigFirewallServiceCategory configFirewallServiceCategory;

	/**
	 * 方向 上行 & 下行
	 */
	private String direction;

	/**
	 * 结束端口
	 */
	private Integer endPort;

	/**
	 * 所属FirewallService
	 */
	private Integer firewallService;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 协议 TCP & UDP
	 */
	private String protocol;

	/**
	 * 起始端口
	 */
	private Integer startPort;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigFirewallServiceCategoryHistory() {
	}

	@Column(name = "action", length = 100)
	public String getAction() {
		return action;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public ConfigFirewallServiceCategory getConfigFirewallServiceCategory() {
		return configFirewallServiceCategory;
	}

	@Column(name = "direction", length = 100)
	public String getDirection() {
		return direction;
	}

	@Column(name = "end_port")
	public Integer getEndPort() {
		return endPort;
	}

	@Column(name = "firewall_service")
	public Integer getFirewallService() {
		return firewallService;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "protocol", length = 100)
	public String getProtocol() {
		return protocol;
	}

	@Column(name = "start_port")
	public Integer getStartPort() {
		return startPort;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setConfigFirewallServiceCategory(ConfigFirewallServiceCategory configFirewallServiceCategory) {
		this.configFirewallServiceCategory = configFirewallServiceCategory;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public void setEndPort(Integer endPort) {
		this.endPort = endPort;
	}

	public void setFirewallService(Integer firewallService) {
		this.firewallService = firewallService;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}

	public void setStartPort(Integer startPort) {
		this.startPort = startPort;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
