package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ConfigRouterStaticHistory generated by hbm2java
 */
@Entity
@Table(name = "config_router_static_history", schema = "public")
public class ConfigRouterStaticHistory extends BasicEntity {

	private ConfigRouterStatic configRouterStatic;
	/**
	 * 所属公网IP
	 */
	private Integer eip;

	/**
	 * 所属ISP
	 */
	private Integer isp;

	/**
	 * 防火墙策略ID,唯一递增
	 */
	private Integer policyId;

	/**
	 * 防火墙路由ID,唯一递增
	 */
	private Integer routerId;

	/**
	 * 网段
	 */
	private String segment;

	/**
	 * 所属Tenants
	 */
	private Integer tenants;

	public ConfigRouterStaticHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public ConfigRouterStatic getConfigRouterStatic() {
		return configRouterStatic;
	}

	@Column(name = "eip")
	public Integer getEip() {
		return eip;
	}

	@Column(name = "isp")
	public Integer getIsp() {
		return isp;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	@Column(name = "router_id")
	public Integer getRouterId() {
		return routerId;
	}

	@Column(name = "segment", length = 100)
	public String getSegment() {
		return segment;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setConfigRouterStatic(ConfigRouterStatic configRouterStatic) {
		this.configRouterStatic = configRouterStatic;
	}

	public void setEip(Integer eip) {
		this.eip = eip;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public void setRouterId(Integer routerId) {
		this.routerId = routerId;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
