package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * DeviceSpecHistory generated by hbm2java
 */
@Entity
@Table(name = "device_spec_history", schema = "public")
public class DeviceSpecHistory extends BasicEntity {

	private Integer brand;
	private String cpuModel;
	private Integer cpuNumber;
	private DeviceSpec deviceSpec;
	private Integer deviceType;
	private Date endDate;
	private Integer hdNumber;
	private Integer height;
	private Integer idc;
	private Integer maintenance;
	private Integer nicNumber;
	private Integer power;
	private Integer ramNumber;
	private String remark;

	public DeviceSpecHistory() {
	}

	@Column(name = "brand")
	public Integer getBrand() {
		return brand;
	}

	@Column(name = "cpu_model")
	public String getCpuModel() {
		return cpuModel;
	}

	@Column(name = "cpu_number")
	public Integer getCpuNumber() {
		return cpuNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public DeviceSpec getDeviceSpec() {
		return deviceSpec;
	}

	@Column(name = "device_type")
	public Integer getDeviceType() {
		return deviceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return endDate;
	}

	@Column(name = "hd_number")
	public Integer getHdNumber() {
		return hdNumber;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return height;
	}

	@Column(name = "idc")
	public Integer getIdc() {
		return idc;
	}

	@Column(name = "maintenance")
	public Integer getMaintenance() {
		return maintenance;
	}

	@Column(name = "nic_number")
	public Integer getNicNumber() {
		return nicNumber;
	}

	@Column(name = "power")
	public Integer getPower() {
		return power;
	}

	@Column(name = "ram_number")
	public Integer getRamNumber() {
		return ramNumber;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setCpuModel(String cpuModel) {
		this.cpuModel = cpuModel;
	}

	public void setCpuNumber(Integer cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDeviceSpec(DeviceSpec deviceSpec) {
		this.deviceSpec = deviceSpec;
	}

	public void setDeviceType(Integer deviceType) {
		this.deviceType = deviceType;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setHdNumber(Integer hdNumber) {
		this.hdNumber = hdNumber;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setMaintenance(Integer maintenance) {
		this.maintenance = maintenance;
	}

	public void setNicNumber(Integer nicNumber) {
		this.nicNumber = nicNumber;
	}

	public void setPower(Integer power) {
		this.power = power;
	}

	public void setRamNumber(Integer ramNumber) {
		this.ramNumber = ramNumber;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
