package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * EsgPolicy generated by hbm2java
 */
@Entity
@Table(name = "dns_policy", schema = "public")
public class DnsPolicy extends BasicEntity {

	private Integer dns;
	private Set<DnsPolicyHistory> dnsPolicyHistories = new HashSet<DnsPolicyHistory>(0);
	private Integer dnsProtocol;
	private String ipaddress;

	private Integer port;

	public DnsPolicy() {
	}

	@Column(name = "dns")
	public Integer getDns() {
		return dns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dnsPolicy")
	public Set<DnsPolicyHistory> getDnsPolicyHistories() {
		return dnsPolicyHistories;
	}

	@Column(name = "dns_protocol")
	public Integer getDnsProtocol() {
		return dnsProtocol;
	}

	@Column(name = "ipaddress", length = 100)
	public String getIpaddress() {
		return ipaddress;
	}

	@Column(name = "port")
	public Integer getPort() {
		return port;
	}

	public void setDns(Integer dns) {
		this.dns = dns;
	}

	public void setDnsPolicyHistories(Set<DnsPolicyHistory> dnsPolicyHistories) {
		this.dnsPolicyHistories = dnsPolicyHistories;
	}

	public void setDnsProtocol(Integer dnsProtocol) {
		this.dnsProtocol = dnsProtocol;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

}
