package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EsgPolicy generated by hbm2java
 */
@Entity
@Table(name = "dns_policy", schema = "public")
public class DnsPolicy extends BasicEntity {

	private Integer dns;
	private Integer esgProtocol;
	private Integer port;
	private Set<DnsPolicyHistory> dnsPolicyHistories = new HashSet<DnsPolicyHistory>(0);

	public DnsPolicy() {
	}

	@Column(name = "dns")
	public Integer getDns() {
		return dns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dnsPolicy")
	public Set<DnsPolicyHistory> getDnsPolicyHistories() {
		return dnsPolicyHistories;
	}

	@Column(name = "esg_protocol")
	public Integer getEsgProtocol() {
		return this.esgProtocol;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	public void setDns(Integer dns) {
		this.dns = dns;
	}

	public void setDnsPolicyHistories(Set<DnsPolicyHistory> dnsPolicyHistories) {
		this.dnsPolicyHistories = dnsPolicyHistories;
	}

	public void setEsgProtocol(Integer esgProtocol) {
		this.esgProtocol = esgProtocol;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

}
