package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * EsgPolicyHistory generated by hbm2java
 */
@Entity
@Table(name = "dns_policy_history", schema = "public")
public class DnsPolicyHistory extends BasicEntity {

	private Integer dns;
	private DnsPolicy dnsPolicy;
	private Integer dnsProtocol;
	private Date endDate;
	private String ipaddress;
	private Integer port;

	public DnsPolicyHistory() {
	}

	@Column(name = "dns")
	public Integer getDns() {
		return dns;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public DnsPolicy getDnsPolicy() {
		return dnsPolicy;
	}

	@Column(name = "dns_protocol")
	public Integer getDnsProtocol() {
		return dnsProtocol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return endDate;
	}

	@Column(name = "ipaddress", length = 100)
	public String getIpaddress() {
		return ipaddress;
	}

	@Column(name = "port")
	public Integer getPort() {
		return port;
	}

	public void setDns(Integer dns) {
		this.dns = dns;
	}

	public void setDnsPolicy(DnsPolicy dnsPolicy) {
		this.dnsPolicy = dnsPolicy;
	}

	public void setDnsProtocol(Integer dnsProtocol) {
		this.dnsProtocol = dnsProtocol;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

}
