package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceBasic;

/**
 * Ecs generated by hbm2java
 */
@Entity
@Table(name = "ecs", schema = "public")
public class Ecs extends ServiceBasic {

	private Integer ipaddress;
	private Integer ecsSpec;
	private Integer server;
	private Integer ecsStatus;
	private Set<EcsHistory> ecsHistories = new HashSet<EcsHistory>(0);

	public Ecs() {
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return ecsSpec;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	@Column(name = "server")
	public Integer getServer() {
		return server;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	@Column(name = "ecs_status")
	public Integer getEcsStatus() {
		return ecsStatus;
	}

	public void setEcsStatus(Integer ecsStatus) {
		this.ecsStatus = ecsStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecs")
	public Set<EcsHistory> getEcsHistories() {
		return ecsHistories;
	}

	public void setEcsHistories(Set<EcsHistory> ecsHistories) {
		this.ecsHistories = ecsHistories;
	}

}
