package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceBasic;

/**
 * Ecs generated by hbm2java
 */
@Entity
@Table(name = "ecs", schema = "public")
public class Ecs extends ServiceBasic {

	private String adapterName;
	private String cpuNumber;
	private String datastoreName;
	private String diskSize;
	private Set<EcsHistory> ecsHistories = new HashSet<EcsHistory>(0);
	private Integer ecsSpec;
	private Integer ecsStatus;
	private Integer ecsType;
	private Integer ipaddress;
	private Boolean isDesktop;
	private Boolean isGpu;
	private String macAddress;
	private String memorySize;
	private String osName;
	private Integer server;
	private Integer subnet;

	public Ecs() {
	}

	@Column(name = "adapter_name", length = 200)
	public String getAdapterName() {
		return adapterName;
	}

	@Column(name = "cpu_number", length = 100)
	public String getCpuNumber() {
		return cpuNumber;
	}

	@Column(name = "datastore_name", length = 200)
	public String getDatastoreName() {
		return datastoreName;
	}

	@Column(name = "disk_size", length = 100)
	public String getDiskSize() {
		return diskSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecs")
	public Set<EcsHistory> getEcsHistories() {
		return ecsHistories;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return ecsSpec;
	}

	@Column(name = "ecs_status")
	public Integer getEcsStatus() {
		return ecsStatus;
	}

	@Column(name = "ecs_type")
	public Integer getEcsType() {
		return ecsType;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	@Column(name = "is_desktop")
	public Boolean getIsDesktop() {
		return isDesktop;
	}

	@Column(name = "is_gpu")
	public Boolean getIsGpu() {
		return isGpu;
	}

	@Column(name = "mac_address", length = 100)
	public String getMacAddress() {
		return macAddress;
	}

	@Column(name = "memory_size", length = 100)
	public String getMemorySize() {
		return memorySize;
	}

	@Column(name = "os_name", length = 100)
	public String getOsName() {
		return osName;
	}

	@Column(name = "server")
	public Integer getServer() {
		return server;
	}

	@Column(name = "subnet")
	public Integer getSubnet() {
		return subnet;
	}

	public void setAdapterName(String adapterName) {
		this.adapterName = adapterName;
	}

	public void setCpuNumber(String cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDatastoreName(String datastoreName) {
		this.datastoreName = datastoreName;
	}

	public void setDiskSize(String diskSize) {
		this.diskSize = diskSize;
	}

	public void setEcsHistories(Set<EcsHistory> ecsHistories) {
		this.ecsHistories = ecsHistories;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	public void setEcsStatus(Integer ecsStatus) {
		this.ecsStatus = ecsStatus;
	}

	public void setEcsType(Integer ecsType) {
		this.ecsType = ecsType;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setIsDesktop(Boolean isDesktop) {
		this.isDesktop = isDesktop;
	}

	public void setIsGpu(Boolean isGpu) {
		this.isGpu = isGpu;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public void setMemorySize(String memorySize) {
		this.memorySize = memorySize;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setSubnet(Integer subnet) {
		this.subnet = subnet;
	}

}
