package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * EcsHistory generated by hbm2java
 */
@Entity
@Table(name = "ecs_history", schema = "public")
public class EcsHistory extends ServiceHistoryBasic {

	private Ecs ecs;
	private Integer ipaddress;
	private Integer ecsSpec;
	private Integer server;
	private Integer ecsStatus;
	private String osName;
	private String adapterName;
	private String cpuNumber;
	private String memorySize;
	private String datastoreName;
	private String diskSize;

	public EcsHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Ecs getEcs() {
		return ecs;
	}

	public void setEcs(Ecs ecs) {
		this.ecs = ecs;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return ecsSpec;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	@Column(name = "server")
	public Integer getServer() {
		return server;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	@Column(name = "ecs_status")
	public Integer getEcsStatus() {
		return ecsStatus;
	}

	public void setEcsStatus(Integer ecsStatus) {
		this.ecsStatus = ecsStatus;
	}

	@Column(name = "os_name", length = 100)
	public String getOsName() {
		return osName;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	@Column(name = "adapter_name", length = 200)
	public String getAdapterName() {
		return adapterName;
	}

	public void setAdapterName(String adapterName) {
		this.adapterName = adapterName;
	}

	@Column(name = "cpu_number", length = 100)
	public String getCpuNumber() {
		return cpuNumber;
	}

	public void setCpuNumber(String cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	@Column(name = "memory_size", length = 100)
	public String getMemorySize() {
		return memorySize;
	}

	public void setMemorySize(String memorySize) {
		this.memorySize = memorySize;
	}

	@Column(name = "datastore_name", length = 200)
	public String getDatastoreName() {
		return datastoreName;
	}

	public void setDatastoreName(String datastoreName) {
		this.datastoreName = datastoreName;
	}

	@Column(name = "disk_size", length = 100)
	public String getDiskSize() {
		return diskSize;
	}

	public void setDiskSize(String diskSize) {
		this.diskSize = diskSize;
	}

}
