package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * EcsSpecHistory generated by hbm2java
 */
@Entity
@Table(name = "ecs_spec_history", schema = "public")
public class EcsSpecHistory extends BasicEntity {

	private EcsSpec ecsSpec;
	private Integer ecsType;
	private Date endDate;
	private String imageName;
	private Integer osType;
	private Integer producedNumber;

	private String remark;

	public EcsSpecHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public EcsSpec getEcsSpec() {
		return ecsSpec;
	}

	@Column(name = "ecs_type")
	public Integer getEcsType() {
		return ecsType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return endDate;
	}

	@Column(name = "image_name", length = 200)
	public String getImageName() {
		return imageName;
	}

	@Column(name = "os_type")
	public Integer getOsType() {
		return osType;
	}

	@Column(name = "produced_number")
	public Integer getProducedNumber() {
		return producedNumber;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	public void setEcsSpec(EcsSpec ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	public void setEcsType(Integer ecsType) {
		this.ecsType = ecsType;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public void setOsType(Integer osType) {
		this.osType = osType;
	}

	public void setProducedNumber(Integer producedNumber) {
		this.producedNumber = producedNumber;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
