package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * EipHistory generated by hbm2java
 */
@Entity
@Table(name = "eip_history", schema = "public")
public class EipHistory extends ServiceHistoryBasic {

	private Integer bandwidth;
	private Eip eip;
	private Integer eipStatus;
	private Integer ipaddress;
	private Integer isp;
	private Integer router;

	public EipHistory() {
	}

	@Column(name = "bandwidth")
	public Integer getBandwidth() {
		return bandwidth;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Eip getEip() {
		return eip;
	}

	@Column(name = "eip_status")
	public Integer getEipStatus() {
		return eipStatus;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	@Column(name = "isp")
	public Integer getIsp() {
		return isp;
	}

	@Column(name = "router")
	public Integer getRouter() {
		return router;
	}

	public void setBandwidth(Integer bandwidth) {
		this.bandwidth = bandwidth;
	}

	public void setEip(Eip eip) {
		this.eip = eip;
	}

	public void setEipStatus(Integer eipStatus) {
		this.eipStatus = eipStatus;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

	public void setRouter(Integer router) {
		this.router = router;
	}

}
