package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceBasic;

/**
 * Elb generated by hbm2java
 */
@Entity
@Table(name = "elb", schema = "public")
public class Elb extends ServiceBasic {

	private Integer ipaddress;
	private Set<ElbHistory> elbHistories = new HashSet<ElbHistory>(0);

	public Elb() {
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elb")
	public Set<ElbHistory> getElbHistories() {
		return elbHistories;
	}

	public void setElbHistories(Set<ElbHistory> elbHistories) {
		this.elbHistories = elbHistories;
	}

}
