package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * ElbHistory generated by hbm2java
 */
@Entity
@Table(name = "elb_history", schema = "public")
public class ElbHistory extends ServiceHistoryBasic {

	private Elb elb;
	private Integer ipaddress;

	public ElbHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Elb getElb() {
		return elb;
	}

	public void setElb(Elb elb) {
		this.elb = elb;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

}
