package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * ElbPolicy generated by hbm2java
 */
@Entity
@Table(name = "elb_policy", schema = "public")
public class ElbPolicy extends BasicEntity {

	private Integer elb;
	private Set<ElbPolicyHistory> elbPolicyHistories = new HashSet<ElbPolicyHistory>(0);
	private Integer elbProtocol;
	private String ipaddress;
	private Integer sourcePort;

	private Integer targetPort;

	public ElbPolicy() {
	}

	@Column(name = "elb")
	public Integer getElb() {
		return elb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elbPolicy")
	public Set<ElbPolicyHistory> getElbPolicyHistories() {
		return elbPolicyHistories;
	}

	@Column(name = "elb_protocol")
	public Integer getElbProtocol() {
		return elbProtocol;
	}

	@Column(name = "ipaddress", length = 100)
	public String getIpaddress() {
		return ipaddress;
	}

	@Column(name = "source_port")
	public Integer getSourcePort() {
		return sourcePort;
	}

	@Column(name = "target_port")
	public Integer getTargetPort() {
		return targetPort;
	}

	public void setElb(Integer elb) {
		this.elb = elb;
	}

	public void setElbPolicyHistories(Set<ElbPolicyHistory> elbPolicyHistories) {
		this.elbPolicyHistories = elbPolicyHistories;
	}

	public void setElbProtocol(Integer elbProtocol) {
		this.elbProtocol = elbProtocol;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setSourcePort(Integer sourcePort) {
		this.sourcePort = sourcePort;
	}

	public void setTargetPort(Integer targetPort) {
		this.targetPort = targetPort;
	}

}
