package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * EsgHistory generated by hbm2java
 */
@Entity
@Table(name = "esg_history", schema = "public")
public class EsgHistory extends ServiceHistoryBasic {

	private Esg esg;
	private Integer aclNumber;
	private Boolean isDefault;

	public EsgHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Esg getEsg() {
		return esg;
	}

	public void setEsg(Esg esg) {
		this.esg = esg;
	}

	@Column(name = "acl_number")
	public Integer getAclNumber() {
		return aclNumber;
	}

	public void setAclNumber(Integer aclNumber) {
		this.aclNumber = aclNumber;
	}

	@Column(name = "is_default")
	public Boolean getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

}
