package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * EsgPolicy generated by hbm2java
 */
@Entity
@Table(name = "esg_policy", schema = "public")
public class EsgPolicy extends BasicEntity {

	private Integer esg;
	private Integer policyType;
	private String sourceIp;
	private String targetIp;
	private Integer port;
	private Set<EsgPolicyHistory> esgPolicyHistories = new HashSet<EsgPolicyHistory>(0);

	public EsgPolicy() {
	}

	@Column(name = "esg")
	public Integer getEsg() {
		return esg;
	}

	public void setEsg(Integer esg) {
		this.esg = esg;
	}

	@Column(name = "policy_type")
	public Integer getPolicyType() {
		return policyType;
	}

	public void setPolicyType(Integer policyType) {
		this.policyType = policyType;
	}

	@Column(name = "source_ip")
	public String getSourceIp() {
		return sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	@Column(name = "target_ip")
	public String getTargetIp() {
		return targetIp;
	}

	public void setTargetIp(String targetIp) {
		this.targetIp = targetIp;
	}

	@Column(name = "port")
	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "esgPolicy")
	public Set<EsgPolicyHistory> getEsgPolicyHistories() {
		return esgPolicyHistories;
	}

	public void setEsgPolicyHistories(Set<EsgPolicyHistory> esgPolicyHistories) {
		this.esgPolicyHistories = esgPolicyHistories;
	}

}
