package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * EsgPolicyHistory generated by hbm2java
 */
@Entity
@Table(name = "esg_policy_history", schema = "public")
public class EsgPolicyHistory extends BasicEntity {

	private EsgPolicy esgPolicy;
	private Date endDate;
	private Integer esg;
	private Integer policyType;
	private String sourceIp;
	private String targetIp;
	private Integer port;

	public EsgPolicyHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public EsgPolicy getEsgPolicy() {
		return esgPolicy;
	}

	public void setEsgPolicy(EsgPolicy esgPolicy) {
		this.esgPolicy = esgPolicy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "esg")
	public Integer getEsg() {
		return esg;
	}

	public void setEsg(Integer esg) {
		this.esg = esg;
	}

	@Column(name = "policy_type")
	public Integer getPolicyType() {
		return policyType;
	}

	public void setPolicyType(Integer policyType) {
		this.policyType = policyType;
	}

	@Column(name = "source_ip")
	public String getSourceIp() {
		return sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	@Column(name = "target_ip")
	public String getTargetIp() {
		return targetIp;
	}

	public void setTargetIp(String targetIp) {
		this.targetIp = targetIp;
	}

	@Column(name = "port")
	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

}
