package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * FirewallPortHistory generated by hbm2java
 */
@Entity
@Table(name = "firewall_port_history", schema = "public")
public class FirewallPortHistory extends PortHistoryBasic {

	private FirewallPort firewallPort;
	private Integer firewall;

	public FirewallPortHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public FirewallPort getFirewallPort() {
		return firewallPort;
	}

	public void setFirewallPort(FirewallPort firewallPort) {
		this.firewallPort = firewallPort;
	}

	@Column(name = "firewall")
	public Integer getFirewall() {
		return firewall;
	}

	public void setFirewall(Integer firewall) {
		this.firewall = firewall;
	}

}
