package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortBasic;

/**
 * FirewallPort generated by hbm2java
 */
@Entity
@Table(name = "firewall_port", schema = "public")
public class FirewallPort extends PortBasic {

	private Integer firewall;
	private Set<FirewallPortHistory> firewallPortHistories = new HashSet<FirewallPortHistory>(0);

	public FirewallPort() {
	}

	@Column(name = "firewall")
	public Integer getFirewall() {
		return firewall;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firewallPort")
	public Set<FirewallPortHistory> getFirewallPortHistories() {
		return firewallPortHistories;
	}

	public void setFirewall(Integer firewall) {
		this.firewall = firewall;
	}

	public void setFirewallPortHistories(Set<FirewallPortHistory> firewallPortHistories) {
		this.firewallPortHistories = firewallPortHistories;
	}

}
