package com.sobey.cmdbuild.entity;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.DeviceHistoryBasic;

/**
 * FirewallHistory generated by hbm2java
 */
@Entity
@Table(name = "firewall_history", schema = "public")
public class FirewallHistory extends DeviceHistoryBasic {

	private Firewall firewall;

	public FirewallHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Firewall getFirewall() {
		return this.firewall;
	}

	public void setFirewall(Firewall firewall) {
		this.firewall = firewall;
	}

}
