package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceBasic;

/**
 * Ecs generated by hbm2java
 */
@Entity
@Table(name = "firewall_service", schema = "public")
public class FirewallService extends ServiceBasic {

	private Set<FirewallServiceHistory> firewallServiceHistories = new HashSet<FirewallServiceHistory>(0);

	public FirewallService() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firewallService")
	public Set<FirewallServiceHistory> getFirewallServiceHistories() {
		return firewallServiceHistories;
	}

	public void setFirewallServiceHistories(Set<FirewallServiceHistory> firewallServiceHistories) {
		this.firewallServiceHistories = firewallServiceHistories;
	}

}
