package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentHistoryBasic;

/**
 * HardDiskHistory generated by hbm2java
 */
@Entity
@Table(name = "hard_disk_history", schema = "public")
public class HardDiskHistory extends ComponentHistoryBasic {

	private HardDisk hardDisk;
	private Integer rotationalSpeed;
	private Integer hdSize;
	private Integer diskType;

	public HardDiskHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public HardDisk getHardDisk() {
		return hardDisk;
	}

	public void setHardDisk(HardDisk hardDisk) {
		this.hardDisk = hardDisk;
	}

	@Column(name = "rotational_speed")
	public Integer getRotationalSpeed() {
		return rotationalSpeed;
	}

	public void setRotationalSpeed(Integer rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

	@Column(name = "hd_size")
	public Integer getHdSize() {
		return hdSize;
	}

	public void setHdSize(Integer hdSize) {
		this.hdSize = hdSize;
	}

	@Column(name = "disk_type")
	public Integer getDiskType() {
		return diskType;
	}

	public void setDiskType(Integer diskType) {
		this.diskType = diskType;
	}

}
