package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentBasic;

/**
 * HardDisk generated by hbm2java
 */
@Entity
@Table(name = "hard_disk", schema = "public")
public class HardDisk extends ComponentBasic {

	private Integer diskType;
	private Set<HardDiskHistory> hardDiskHistories = new HashSet<HardDiskHistory>(0);
	private Integer hdSize;
	private Integer rotationalSpeed;

	public HardDisk() {
	}

	@Column(name = "disk_type")
	public Integer getDiskType() {
		return diskType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hardDisk")
	public Set<HardDiskHistory> getHardDiskHistories() {
		return hardDiskHistories;
	}

	@Column(name = "hd_size")
	public Integer getHdSize() {
		return hdSize;
	}

	@Column(name = "rotational_speed")
	public Integer getRotationalSpeed() {
		return rotationalSpeed;
	}

	public void setDiskType(Integer diskType) {
		this.diskType = diskType;
	}

	public void setHardDiskHistories(Set<HardDiskHistory> hardDiskHistories) {
		this.hardDiskHistories = hardDiskHistories;
	}

	public void setHdSize(Integer hdSize) {
		this.hdSize = hdSize;
	}

	public void setRotationalSpeed(Integer rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

}
