package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * Idc generated by hbm2java
 */
@Entity
@Table(name = "idc", schema = "public")
public class Idc extends BasicEntity {

	private String city;
	private String zip;
	private String address;
	private String phone;
	private String remark;
	private Set<IdcHistory> idcHistories = new HashSet<IdcHistory>(0);

	public Idc() {
	}

	@Column(name = "city", length = 100)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip", length = 200)
	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idc")
	public Set<IdcHistory> getIdcHistories() {
		return idcHistories;
	}

	public void setIdcHistories(Set<IdcHistory> idcHistories) {
		this.idcHistories = idcHistories;
	}

}
