package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * Ipaddress generated by hbm2java
 */
@Entity
@Table(name = "ipaddress", schema = "public")
public class Ipaddress extends BasicEntity {

	private Integer vlan;
	private Integer idc;
	private Integer isp;
	private Integer ipaddressPool;
	private Integer ipaddressStatus;
	private String netMask;
	private String remark;
	private String gateway;

	private Set<IpaddressHistory> ipaddressHistories = new HashSet<IpaddressHistory>(0);

	public Ipaddress() {
	}

	@Column(name = "vlan")
	public Integer getVlan() {
		return vlan;
	}

	public void setVlan(Integer vlan) {
		this.vlan = vlan;
	}

	@Column(name = "idc")
	public Integer getIdc() {
		return idc;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	@Column(name = "isp")
	public Integer getIsp() {
		return isp;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

	@Column(name = "ipaddress_pool")
	public Integer getIpaddressPool() {
		return ipaddressPool;
	}

	public void setIpaddressPool(Integer ipaddressPool) {
		this.ipaddressPool = ipaddressPool;
	}

	@Column(name = "ipaddress_status")
	public Integer getIpaddressStatus() {
		return ipaddressStatus;
	}

	public void setIpaddressStatus(Integer ipaddressStatus) {
		this.ipaddressStatus = ipaddressStatus;
	}

	@Column(name = "net_mask", length = 100)
	public String getNetMask() {
		return netMask;
	}

	public void setNetMask(String netMask) {
		this.netMask = netMask;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "gateway", length = 100)
	public String getGateway() {
		return gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ipaddress")
	public Set<IpaddressHistory> getIpaddressHistories() {
		return ipaddressHistories;
	}

	public void setIpaddressHistories(Set<IpaddressHistory> ipaddressHistories) {
		this.ipaddressHistories = ipaddressHistories;
	}

}
