package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * LoadBalancerPortHistory generated by hbm2java
 */
@Entity
@Table(name = "load_balancer_port_history", schema = "public")
public class LoadBalancerPortHistory extends PortHistoryBasic {

	private Integer loadBalancer;
	private LoadBalancerPort loadBalancerPort;

	public LoadBalancerPortHistory() {
	}

	@Column(name = "\"loadBalancer\"")
	public Integer getLoadBalancer() {
		return loadBalancer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public LoadBalancerPort getLoadBalancerPort() {
		return loadBalancerPort;
	}

	public void setLoadBalancer(Integer loadBalancer) {
		this.loadBalancer = loadBalancer;
	}

	public void setLoadBalancerPort(LoadBalancerPort loadBalancerPort) {
		this.loadBalancerPort = loadBalancerPort;
	}

}
