package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.DeviceBasic;

/**
 * LoadBalancer generated by hbm2java
 */
@Entity
@Table(name = "load_balancer", schema = "public")
public class LoadBalancer extends DeviceBasic {

	private Set<LoadBalancerHistory> loadBalancerHistories = new HashSet<LoadBalancerHistory>(0);

	public LoadBalancer() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loadBalancer")
	public Set<LoadBalancerHistory> getLoadBalancerHistories() {
		return loadBalancerHistories;
	}

	public void setLoadBalancerHistories(Set<LoadBalancerHistory> loadBalancerHistories) {
		this.loadBalancerHistories = loadBalancerHistories;
	}

}
