package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentHistoryBasic;

/**
 * MemoryHistory generated by hbm2java
 */
@Entity
@Table(name = "memory_history", schema = "public")
public class MemoryHistory extends ComponentHistoryBasic {

	private Integer frequency;
	private Memory memory;
	private Integer size;

	public MemoryHistory() {
	}

	@Column(name = "frequency")
	public Integer getFrequency() {
		return frequency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Memory getMemory() {
		return memory;
	}

	@Column(name = "size")
	public Integer getSize() {
		return size;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public void setMemory(Memory memory) {
		this.memory = memory;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

}
