package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentBasic;

/**
 * Memory generated by hbm2java
 */
@Entity
@Table(name = "memory", schema = "public")
public class Memory extends ComponentBasic {

	private Integer frequency;
	private Integer size;
	private Set<MemoryHistory> memoryHistories = new HashSet<MemoryHistory>(0);

	public Memory() {
	}

	@Column(name = "frequency")
	public Integer getFrequency() {
		return frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	@Column(name = "size")
	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memory")
	public Set<MemoryHistory> getMemoryHistories() {
		return memoryHistories;
	}

	public void setMemoryHistories(Set<MemoryHistory> memoryHistories) {
		this.memoryHistories = memoryHistories;
	}

}
