package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentBasic;

/**
 * Nic generated by hbm2java
 */
@Entity
@Table(name = "nic", schema = "public")
public class Nic extends ComponentBasic {

	private Set<NicHistory> nicHistories = new HashSet<NicHistory>(0);
	private Integer nicRate;
	private Integer portNumber;
	private String virtualSwitchName;

	public Nic() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nic")
	public Set<NicHistory> getNicHistories() {
		return nicHistories;
	}

	@Column(name = "nic_rate")
	public Integer getNicRate() {
		return nicRate;
	}

	@Column(name = "port_num")
	public Integer getPortNumber() {
		return portNumber;
	}

	@Column(name = "virtual_switch_name", length = 100)
	public String getVirtualSwitchName() {
		return virtualSwitchName;
	}

	public void setNicHistories(Set<NicHistory> nicHistories) {
		this.nicHistories = nicHistories;
	}

	public void setNicRate(Integer nicRate) {
		this.nicRate = nicRate;
	}

	public void setPortNumber(Integer portNumber) {
		this.portNumber = portNumber;
	}

	public void setVirtualSwitchName(String virtualSwitchName) {
		this.virtualSwitchName = virtualSwitchName;
	}

}
