package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentHistoryBasic;

/**
 * NicHistory generated by hbm2java
 */
@Entity
@Table(name = "nic_history", schema = "public")
public class NicHistory extends ComponentHistoryBasic {

	private Nic nic;
	private Integer nicRate;
	private Integer portNumber;
	private String virtualSwitchName;

	public NicHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Nic getNic() {
		return nic;
	}

	@Column(name = "nic_rate")
	public Integer getNicRate() {
		return nicRate;
	}

	@Column(name = "port_num")
	public Integer getPortNumber() {
		return portNumber;
	}

	@Column(name = "virtual_switch_name", length = 100)
	public String getVirtualSwitchName() {
		return virtualSwitchName;
	}

	public void setNic(Nic nic) {
		this.nic = nic;
	}

	public void setNicRate(Integer nicRate) {
		this.nicRate = nicRate;
	}

	public void setPortNumber(Integer portNumber) {
		this.portNumber = portNumber;
	}

	public void setVirtualSwitchName(String virtualSwitchName) {
		this.virtualSwitchName = virtualSwitchName;
	}

}
