package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * NicPortHistory generated by hbm2java
 */
@Entity
@Table(name = "nic_port_history", schema = "public")
public class NicPortHistory extends PortHistoryBasic {

	private Integer nic;
	private NicPort nicPort;

	public NicPortHistory() {
	}

	@Column(name = "nic")
	public Integer getNic() {
		return nic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public NicPort getNicPort() {
		return nicPort;
	}

	public void setNic(Integer nic) {
		this.nic = nic;
	}

	public void setNicPort(NicPort nicPort) {
		this.nicPort = nicPort;
	}

}
