package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortBasic;

/**
 * NicPort generated by hbm2java
 */
@Entity
@Table(name = "nic_port", schema = "public")
public class NicPort extends PortBasic {

	private Integer nic;
	private Set<NicPortHistory> nicPortHistories = new HashSet<NicPortHistory>(0);

	public NicPort() {
	}

	@Column(name = "nic")
	public Integer getNic() {
		return nic;
	}

	public void setNic(Integer nic) {
		this.nic = nic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nicPort")
	public Set<NicPortHistory> getNicPortHistories() {
		return nicPortHistories;
	}

	public void setNicPortHistories(Set<NicPortHistory> nicPortHistories) {
		this.nicPortHistories = nicPortHistories;
	}

}
