package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * RackHistory generated by hbm2java
 */
@Entity
@Table(name = "rack_history", schema = "public")
public class RackHistory extends BasicEntity {

	private Integer brand;
	private Date endDate;
	private String gdzcSn;
	private Integer height;
	private Integer idc;
	private String model;
	private Integer power;
	private Rack rack;
	private String remark;
	private String sn;
	private Integer unitNumber;

	public RackHistory() {
	}

	@Column(name = "brand")
	public Integer getBrand() {
		return brand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return endDate;
	}

	@Column(name = "gdzcsn", length = 100)
	public String getGdzcSn() {
		return gdzcSn;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return height;
	}

	@Column(name = "idc")
	public Integer getIdc() {
		return idc;
	}

	@Column(name = "model", length = 100)
	public String getModel() {
		return model;
	}

	@Column(name = "power")
	public Integer getPower() {
		return power;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Rack getRack() {
		return rack;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	@Column(name = "sn", length = 100)
	public String getSn() {
		return sn;
	}

	@Column(name = "unit_number")
	public Integer getUnitNumber() {
		return unitNumber;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setGdzcSn(String gdzcSn) {
		this.gdzcSn = gdzcSn;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public void setPower(Integer power) {
		this.power = power;
	}

	public void setRack(Rack rack) {
		this.rack = rack;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public void setUnitNumber(Integer unitNumber) {
		this.unitNumber = unitNumber;
	}

}
