package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * RouterHistory generated by hbm2java
 */
@Entity
@Table(name = "router_history", schema = "public")
public class RouterHistory extends ServiceHistoryBasic {

	private String cpuNumber;
	private String diskSize;
	private Integer ecsSpec;
	private Integer eip;
	private Integer firewallService;
	private Integer ipaddress;
	private String memorySize;
	private Router router;

	public RouterHistory() {
	}

	@Column(name = "cpu_number", length = 100)
	public String getCpuNumber() {
		return cpuNumber;
	}

	@Column(name = "disk_size", length = 100)
	public String getDiskSize() {
		return diskSize;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return ecsSpec;
	}

	@Column(name = "eip")
	public Integer getEip() {
		return eip;
	}

	@Column(name = "firewall_service")
	public Integer getFirewallService() {
		return firewallService;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return ipaddress;
	}

	@Column(name = "memory_size", length = 100)
	public String getMemorySize() {
		return memorySize;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Router getRouter() {
		return router;
	}

	public void setCpuNumber(String cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDiskSize(String diskSize) {
		this.diskSize = diskSize;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	public void setEip(Integer eip) {
		this.eip = eip;
	}

	public void setFirewallService(Integer firewallService) {
		this.firewallService = firewallService;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setMemorySize(String memorySize) {
		this.memorySize = memorySize;
	}

	public void setRouter(Router router) {
		this.router = router;
	}

}
