package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * ServerPortHistory generated by hbm2java
 */
@Entity
@Table(name = "server_port_history", schema = "public")
public class ServerPortHistory extends PortHistoryBasic {

	private Integer server;
	private ServerPort serverPort;

	public ServerPortHistory() {
	}

	@Column(name = "server")
	public Integer getServer() {
		return server;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public ServerPort getServerPort() {
		return serverPort;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setServerPort(ServerPort serverPort) {
		this.serverPort = serverPort;
	}

}
