package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.DeviceBasic;

/**
 * Server generated by hbm2java
 */
@Entity
@Table(name = "server", schema = "public")
public class Server extends DeviceBasic {

	private String resgroup;
	private Set<ServerHistory> serverHistories = new HashSet<ServerHistory>(0);

	public Server() {
	}

	@Column(name = "resgroup", length = 100)
	public String getResgroup() {
		return resgroup;
	}

	public void setResgroup(String resgroup) {
		this.resgroup = resgroup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "server")
	public Set<ServerHistory> getServerHistories() {
		return this.serverHistories;
	}

	public void setServerHistories(Set<ServerHistory> serverHistories) {
		this.serverHistories = serverHistories;
	}

}
