package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortBasic;

/**
 * ServerPort generated by hbm2java
 */
@Entity
@Table(name = "server_port", schema = "public")
public class ServerPort extends PortBasic {

	private Integer server;
	private Set<ServerPortHistory> serverPortHistories = new HashSet<ServerPortHistory>(0);

	public ServerPort() {
	}

	@Column(name = "server")
	public Integer getServer() {
		return server;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverPort")
	public Set<ServerPortHistory> getServerPortHistories() {
		return serverPortHistories;
	}

	public void setServerPortHistories(Set<ServerPortHistory> serverPortHistories) {
		this.serverPortHistories = serverPortHistories;
	}

}
