package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * StoragePortHistory generated by hbm2java
 */
@Entity
@Table(name = "storage_port_history", schema = "public")
public class StoragePortHistory extends PortHistoryBasic {

	private Integer storage;
	private StoragePort storagePort;

	public StoragePortHistory() {
	}

	@Column(name = "storage")
	public Integer getStorage() {
		return storage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public StoragePort getStoragePort() {
		return storagePort;
	}

	public void setStorage(Integer storage) {
		this.storage = storage;
	}

	public void setStoragePort(StoragePort storagePort) {
		this.storagePort = storagePort;
	}

}
