package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.DeviceHistoryBasic;

/**
 * StorageHistory generated by hbm2java
 */
@Entity
@Table(name = "storage_history", schema = "public")
public class StorageHistory extends DeviceHistoryBasic {

	private String name;
	private Storage storage;

	public StorageHistory() {
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Storage getStorage() {
		return storage;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setStorage(Storage storage) {
		this.storage = storage;
	}

}
