package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ComponentHistoryBasic;

/**
 * StorageBoxHistory generated by hbm2java
 */
@Entity
@Table(name = "storage_box_history", schema = "public")
public class StorageBoxHistory extends ComponentHistoryBasic {

	private StorageBox storageBox;
	private Integer diskType;
	private Integer diskNumber;

	public StorageBoxHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public StorageBox getStorageBox() {
		return storageBox;
	}

	public void setStorageBox(StorageBox storageBox) {
		this.storageBox = storageBox;
	}

	@Column(name = "disk_type")
	public Integer getDiskType() {
		return diskType;
	}

	public void setDiskType(Integer diskType) {
		this.diskType = diskType;
	}

	@Column(name = "disk_number")
	public Integer getDiskNumber() {
		return diskNumber;
	}

	public void setDiskNumber(Integer diskNumber) {
		this.diskNumber = diskNumber;
	}

}
