package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortBasic;

/**
 * StoragePort generated by hbm2java
 */
@Entity
@Table(name = "storage_port", schema = "public")
public class StoragePort extends PortBasic {

	private Integer storage;
	private Set<StoragePortHistory> storageHistories = new HashSet<StoragePortHistory>(0);

	public StoragePort() {
	}

	@Column(name = "storage")
	public Integer getStorage() {
		return storage;
	}

	public void setStorage(Integer storage) {
		this.storage = storage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storagePort")
	public Set<StoragePortHistory> getStorageHistories() {
		return storageHistories;
	}

	public void setStorageHistories(Set<StoragePortHistory> storageHistories) {
		this.storageHistories = storageHistories;
	}

}
