package com.sobey.cmdbuild.entity;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.DeviceHistoryBasic;

/**
 * SwitchesHistory generated by hbm2java
 */
@Entity
@Table(name = "switches_history", schema = "public")
public class SwitchesHistory extends DeviceHistoryBasic {

	private Switches switches;

	public SwitchesHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Switches getSwitches() {
		return this.switches;
	}

	public void setSwitches(Switches switches) {
		this.switches = switches;
	}

}
