package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.PortHistoryBasic;

/**
 * SwitchPortHistory generated by hbm2java
 */
@Entity
@Table(name = "switch_port_history", schema = "public")
public class SwitchPortHistory extends PortHistoryBasic {

	private SwitchPort switchPort;
	private Integer switches;

	public SwitchPortHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public SwitchPort getSwitchPort() {
		return switchPort;
	}

	public void setSwitchPort(SwitchPort switchPort) {
		this.switchPort = switchPort;
	}

	@Column(name = "switches")
	public Integer getSwitches() {
		return switches;
	}

	public void setSwitches(Integer switches) {
		this.switches = switches;
	}

}
