package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", schema = "public")
public class Tag extends BasicEntity {

	private Integer tenants;
	private Integer parentTag;
	private Integer tagType;
	private String remark;
	private Set<TagHistory> tagHistories = new HashSet<TagHistory>(0);

	public Tag() {
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return tenants;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

	@Column(name = "parent_tag")
	public Integer getParentTag() {
		return parentTag;
	}

	public void setParentTag(Integer parentTag) {
		this.parentTag = parentTag;
	}

	@Column(name = "tag_type")
	public Integer getTagType() {
		return tagType;
	}

	public void setTagType(Integer tagType) {
		this.tagType = tagType;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<TagHistory> getTagHistories() {
		return tagHistories;
	}

	public void setTagHistories(Set<TagHistory> tagHistories) {
		this.tagHistories = tagHistories;
	}

}
