package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.BasicEntity;

/**
 * Tenants generated by hbm2java
 */
@Entity
@Table(name = "tenants", schema = "public")
public class Tenants extends BasicEntity {

	private String accessKey;
	private String company;
	private String email;
	private String phone;
	private String remark;
	private Set<TenantsHistory> tenantsHistories = new HashSet<TenantsHistory>(0);

	public Tenants() {
	}

	@Column(name = "access_key", length = 200)
	public String getAccessKey() {
		return accessKey;
	}

	@Column(name = "company", length = 100)
	public String getCompany() {
		return company;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return email;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return phone;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tenants")
	public Set<TenantsHistory> getTenantsHistories() {
		return tenantsHistories;
	}

	public void setAccessKey(String accessKey) {
		this.accessKey = accessKey;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setTenantsHistories(Set<TenantsHistory> tenantsHistories) {
		this.tenantsHistories = tenantsHistories;
	}

}
