package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceBasic;

/**
 * Vpn generated by hbm2java
 */
@Entity
@Table(name = "vpn", schema = "public")
public class Vpn extends ServiceBasic {

	private Integer policyId;
	private String password;
	private Set<VpnHistory> vpnHistories = new HashSet<VpnHistory>(0);

	public Vpn() {
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vpn")
	public Set<VpnHistory> getVpnHistories() {
		return vpnHistories;
	}

	public void setVpnHistories(Set<VpnHistory> vpnHistories) {
		this.vpnHistories = vpnHistories;
	}

}
