package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * VpnHistory generated by hbm2java
 */
@Entity
@Table(name = "vpn_history", schema = "public")
public class VpnHistory extends ServiceHistoryBasic {

	private Vpn vpn;
	private Integer policyId;
	private String password;

	public VpnHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Vpn getVpn() {
		return vpn;
	}

	public void setVpn(Vpn vpn) {
		this.vpn = vpn;
	}

	@Column(name = "policy_id")
	public Integer getPolicyId() {
		return policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	@Column(name = "remark", length = 100)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
