package com.sobey.cmdbuild.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.sobey.cmdbuild.entity.basic.ServiceHistoryBasic;

/**
 * VpnHistory generated by hbm2java
 */
@Entity
@Table(name = "vpn_history", schema = "public")
public class VpnHistory extends ServiceHistoryBasic {

	private String password;
	private String username;
	private Vpn vpn;

	public VpnHistory() {
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return password;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Vpn getVpn() {
		return vpn;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public void setVpn(Vpn vpn) {
		this.vpn = vpn;
	}

}
