package com.sobey.generate.firewall;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8 2013-12-13T13:56:36.527+08:00 Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://firewall.generate.sobey.com", name = "FirewallSoapService")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FirewallSoapService {

	@WebResult(name = "deleteVPNUserByFirewallResponse", targetNamespace = "http://firewall.generate.sobey.com", partName = "parameters")
	@WebMethod
	public DeleteVPNUserByFirewallResponse deleteVPNUserByFirewall(
			@WebParam(partName = "parameters", name = "deleteVPNUserByFirewall", targetNamespace = "http://firewall.generate.sobey.com") DeleteVPNUserByFirewall parameters);

	@WebResult(name = "createEIPByFirewallResponse", targetNamespace = "http://firewall.generate.sobey.com", partName = "parameters")
	@WebMethod
	public CreateEIPByFirewallResponse createEIPByFirewall(
			@WebParam(partName = "parameters", name = "createEIPByFirewall", targetNamespace = "http://firewall.generate.sobey.com") CreateEIPByFirewall parameters);

	@WebResult(name = "deleteEIPByFirewallResponse", targetNamespace = "http://firewall.generate.sobey.com", partName = "parameters")
	@WebMethod
	public DeleteEIPByFirewallResponse deleteEIPByFirewall(
			@WebParam(partName = "parameters", name = "deleteEIPByFirewall", targetNamespace = "http://firewall.generate.sobey.com") DeleteEIPByFirewall parameters);

	@WebResult(name = "changeVPNUserAccesssAddressByFirewallResponse", targetNamespace = "http://firewall.generate.sobey.com", partName = "parameters")
	@WebMethod
	public ChangeVPNUserAccesssAddressByFirewallResponse changeVPNUserAccesssAddressByFirewall(
			@WebParam(partName = "parameters", name = "changeVPNUserAccesssAddressByFirewall", targetNamespace = "http://firewall.generate.sobey.com") ChangeVPNUserAccesssAddressByFirewall parameters);

	@WebResult(name = "createVPNUserByFirewallResponse", targetNamespace = "http://firewall.generate.sobey.com", partName = "parameters")
	@WebMethod
	public CreateVPNUserByFirewallResponse createVPNUserByFirewall(
			@WebParam(partName = "parameters", name = "createVPNUserByFirewall", targetNamespace = "http://firewall.generate.sobey.com") CreateVPNUserByFirewall parameters);
}
