package com.sobey.generate.firewall;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.8 2013-12-13T15:06:36.050+08:00 Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "FirewallSoapService", wsdlLocation = "file:/C:/Users/Administrator/Documents/GitHub/sobey-cmop/sobey-projects/cmdbuild/src/main/resources/wsdl/firewallSoapService.xml", targetNamespace = "http://firewall.generate.sobey.com")
public class FirewallSoapService_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://firewall.generate.sobey.com", "FirewallSoapService");
	public final static QName FirewallSoapServiceImplPort = new QName("http://firewall.generate.sobey.com",
			"FirewallSoapServiceImplPort");
	static {
		URL url = null;
		try {
			url = new URL(
					"file:/C:/Users/Administrator/Documents/GitHub/sobey-cmop/sobey-projects/cmdbuild/src/main/resources/wsdl/firewallSoapService.xml");
		} catch (MalformedURLException e) {
			java.util.logging.Logger
					.getLogger(FirewallSoapService_Service.class.getName())
					.log(java.util.logging.Level.INFO,
							"Can not initialize the default wsdl from {0}",
							"file:/C:/Users/Administrator/Documents/GitHub/sobey-cmop/sobey-projects/cmdbuild/src/main/resources/wsdl/firewallSoapService.xml");
		}
		WSDL_LOCATION = url;
	}

	public FirewallSoapService_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public FirewallSoapService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FirewallSoapService_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public FirewallSoapService_Service(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public FirewallSoapService_Service(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public FirewallSoapService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns FirewallSoapService
	 */
	@WebEndpoint(name = "FirewallSoapServiceImplPort")
	public FirewallSoapService getFirewallSoapServiceImplPort() {
		return super.getPort(FirewallSoapServiceImplPort, FirewallSoapService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *            the <code>features</code> parameter will have their default values.
	 * @return returns FirewallSoapService
	 */
	@WebEndpoint(name = "FirewallSoapServiceImplPort")
	public FirewallSoapService getFirewallSoapServiceImplPort(WebServiceFeature... features) {
		return super.getPort(FirewallSoapServiceImplPort, FirewallSoapService.class, features);
	}

}
